// @vitest-environment node
import { test, expect, describe, vi, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";

import { runRfcVerificationEmit } from "./verification-evidence.ts";
import type { ForgeCommandInput, ForgeRuntimeContext } from "../../src/types.ts";

const { mockRunProbe } = vi.hoisted(() => ({
  mockRunProbe: vi.fn(),
}));

vi.mock("./acceptance.ts", () => ({
  runProbe: mockRunProbe,
}));

const RFC_FRONTMATTER = (id: string, status: string, probes: Record<string, unknown>[] = []) => {
  const probeYaml = probes
    .map(
      (p) =>
        `  - probe: ${p.probe}\n    path: ${p.path ?? ""}\n    criterion: ${p.criterion ?? ""}`,
    )
    .join("\n");
  return `---\nid: ${id}\ntitle: "Test ${id}"\nstatus: ${status}\nkind: command\nscope: workspace\nowners:\n  - architecture\ncreatedAt: 2026-01-01\nupdatedAt: 2026-01-01\nacceptance:\n${probeYaml}\n---\n\n# ${id}\n## Context\nTest.\n`;
};

const PROBE = { probe: "file-exists", path: "src/index.ts", criterion: "AC-1" };

async function setupWorkspace(opts: {
  rfcs: Array<{ id: string; status: string; probes?: unknown[] }>;
}): Promise<{ workspaceRoot: string; cleanup: () => Promise<void> }> {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "rfc-emit-test-"));
  const rfcDir = path.join(tmpDir, "docs", "rfcs");
  await fs.mkdir(rfcDir, { recursive: true });

  for (const rfc of opts.rfcs) {
    const slug = rfc.id.toLowerCase();
    const probes = rfc.probes ?? [PROBE];
    await fs.writeFile(
      path.join(rfcDir, `${slug}-test.md`),
      RFC_FRONTMATTER(rfc.id, rfc.status, probes),
    );
  }

  return {
    workspaceRoot: tmpDir,
    cleanup: async () => {
      await fs.rm(tmpDir, { recursive: true, force: true });
    },
  };
}

function makeContext(workspaceRoot: string, overrides: Record<string, unknown> = {}) {
  return {
    workspaceRoot,
    logger: { info: () => {} },
    outputFormat: "json" as const,
    commandRegistry: undefined,
    dryRun: false,
    ...overrides,
  };
}

const envelopePath = (root: string, rfcId: string) =>
  path.join(root, "docs", "rfcs", "verification", `${rfcId.toLowerCase()}.generated.yaml`);

beforeEach(() => {
  mockRunProbe.mockReset();
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe("rfc.verification.emit — baseline emission", () => {
  test("writes the emit-canonical structured marker header + envelope", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.emitted).toHaveLength(1);
      expect(result.exitCode).toBe(0);

      const raw = await fs.readFile(envelopePath(workspaceRoot, "RFC-0100"), "utf-8");
      // RFC-1237 canonical format: structured marker keys, not '#' comments.
      expect(raw).toMatch(/^generatedMarker: GENERATED\./);
      expect(raw).toContain("doNotEdit: DO NOT EDIT THIS FILE.");
      expect(raw).toContain("ownerCommand: rfc.verification.emit");
      expect(raw).toContain(
        "regenerateCommand: pnpm exec werkstatt run rfc.verification.emit",
      );
      expect(raw).toContain("rfcId: RFC-0100");
      expect(raw).toContain("overall: pass");
      expect(raw.split("\n").every((line) => !line.startsWith("#"))).toBe(true);
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.emit — RFC-1237 AC-6: dry-run", () => {
  test("context.dryRun (the real werkstatt run --dry-run path) writes zero envelopes", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      // The real CLI path: consumeCommonFlags strips --dry-run from argv into
      // context.dryRun — input.flags carries no "dry-run" key at all.
      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot, { dryRun: true }) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.emitted).toHaveLength(1);
      expect(result.summary).toContain("dry-run");
      await expect(fs.stat(envelopePath(workspaceRoot, "RFC-0100"))).rejects.toThrow();
      // The verification dir itself is also not created under dry-run.
      await expect(
        fs.stat(path.join(workspaceRoot, "docs", "rfcs", "verification")),
      ).rejects.toThrow();
    } finally {
      await cleanup();
    }
  });

  test("input.flags[\"dry-run\"] (direct/programmatic callers) writes zero envelopes", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100", "dry-run": true } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.summary).toContain("dry-run");
      await expect(fs.stat(envelopePath(workspaceRoot, "RFC-0100"))).rejects.toThrow();
    } finally {
      await cleanup();
    }
  });

  test("dry-run still runs probes and reports overall: fail", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: false, detail: "does not exist" });

      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot, { dryRun: true }) as unknown as ForgeRuntimeContext,
      );

      expect(mockRunProbe).toHaveBeenCalledOnce();
      expect(result.data!.emitted[0]?.overall).toBe("fail");
      expect(result.exitCode).toBe(1);
      await expect(fs.stat(envelopePath(workspaceRoot, "RFC-0100"))).rejects.toThrow();
    } finally {
      await cleanup();
    }
  });
});
