// @vitest-environment node
import { test, expect, describe, vi, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { stringify as yamlStringify } from "yaml";

import {
  runRfcVerificationEmit,
  mapWithConcurrency,
  resolveConcurrency,
} from "./verification-evidence.ts";
import type { ForgeCommandInput, ForgeRuntimeContext } from "../../src/types.ts";

const { mockRunProbe } = vi.hoisted(() => ({
  mockRunProbe: vi.fn(),
}));

vi.mock("./acceptance.ts", () => ({
  runProbe: mockRunProbe,
}));

const RFC_FRONTMATTER = (id: string, status: string, probes: Record<string, unknown>[] = []) => {
  const probeYaml = probes
    .map(
      (p) =>
        `  - probe: ${p.probe}\n    path: ${p.path ?? ""}\n    criterion: ${p.criterion ?? ""}`,
    )
    .join("\n");
  return `---\nid: ${id}\ntitle: "Test ${id}"\nstatus: ${status}\nkind: command\nscope: workspace\nowners:\n  - architecture\ncreatedAt: 2026-01-01\nupdatedAt: 2026-01-01\nacceptance:\n${probeYaml}\n---\n\n# ${id}\n## Context\nTest.\n`;
};

const PROBE = { probe: "file-exists", path: "src/index.ts", criterion: "AC-1" };

function makeEnvelope(rfcId: string, overall: "pass" | "fail"): Record<string, unknown> {
  return {
    rfcId,
    title: `Test ${rfcId}`,
    rfcStatus: "implemented",
    emittedAt: "2026-01-01T00:00:00.000Z",
    commit: "abc123",
    workingTreeDirty: false,
    kernelVersion: "1.0.0",
    rfcFileHash: "hash123",
    acceptanceHash: "accHash123",
    probes: [{ probe: PROBE, ok: overall === "pass", detail: "", durationMs: 5 }],
    overall,
  };
}

async function setupWorkspace(opts: {
  rfcs: Array<{ id: string; status: string; probes?: unknown[] }>;
  envelopes?: Array<{ id: string; overall: "pass" | "fail" }>;
}): Promise<{ workspaceRoot: string; cleanup: () => Promise<void> }> {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "rfc-emit-test-"));
  const rfcDir = path.join(tmpDir, "docs", "rfcs");
  const verificationDir = path.join(rfcDir, "verification");
  await fs.mkdir(rfcDir, { recursive: true });

  for (const rfc of opts.rfcs) {
    const slug = rfc.id.toLowerCase();
    const probes = rfc.probes ?? [PROBE];
    await fs.writeFile(
      path.join(rfcDir, `${slug}-test.md`),
      RFC_FRONTMATTER(rfc.id, rfc.status, probes),
    );
  }

  for (const env of opts.envelopes ?? []) {
    await fs.mkdir(verificationDir, { recursive: true });
    await fs.writeFile(
      path.join(verificationDir, `${env.id.toLowerCase()}.generated.yaml`),
      yamlStringify(makeEnvelope(env.id, env.overall)) + "\n",
    );
  }

  return {
    workspaceRoot: tmpDir,
    cleanup: async () => {
      await fs.rm(tmpDir, { recursive: true, force: true });
    },
  };
}

function makeContext(workspaceRoot: string, overrides: Record<string, unknown> = {}) {
  return {
    workspaceRoot,
    logger: { info: () => {} },
    outputFormat: "json" as const,
    commandRegistry: undefined,
    dryRun: false,
    ...overrides,
  };
}

const envelopePath = (root: string, rfcId: string) =>
  path.join(root, "docs", "rfcs", "verification", `${rfcId.toLowerCase()}.generated.yaml`);

beforeEach(() => {
  mockRunProbe.mockReset();
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe("rfc.verification.emit — baseline emission", () => {
  test("writes the emit-canonical structured marker header + envelope", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.emitted).toHaveLength(1);
      expect(result.exitCode).toBe(0);

      const raw = await fs.readFile(envelopePath(workspaceRoot, "RFC-0100"), "utf-8");
      // RFC-1237 canonical format: structured marker keys, not '#' comments.
      expect(raw).toMatch(/^generatedMarker: GENERATED\./);
      expect(raw).toContain("doNotEdit: DO NOT EDIT THIS FILE.");
      expect(raw).toContain("ownerCommand: rfc.verification.emit");
      expect(raw).toContain("regenerateCommand: pnpm exec werkstatt run rfc.verification.emit");
      expect(raw).toContain("rfcId: RFC-0100");
      expect(raw).toContain("overall: pass");
      expect(raw.split("\n").every((line) => !line.startsWith("#"))).toBe(true);
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.emit — sweep delta report", () => {
  test("reports recovered (fail→pass) and regressed (pass→fail) transitions", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [
        { id: "RFC-0100", status: "implemented" },
        { id: "RFC-0101", status: "implemented" },
        { id: "RFC-0102", status: "implemented" },
      ],
      envelopes: [
        { id: "RFC-0100", overall: "fail" },
        { id: "RFC-0101", overall: "pass" },
        { id: "RFC-0102", overall: "fail" },
      ],
    });

    try {
      mockRunProbe
        .mockResolvedValueOnce({ probe: PROBE, ok: true, detail: "exists" })
        .mockResolvedValueOnce({ probe: PROBE, ok: false, detail: "missing" })
        .mockResolvedValueOnce({ probe: PROBE, ok: false, detail: "missing" });

      const result = await runRfcVerificationEmit(
        { flags: { status: "implemented" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.delta).toEqual({
        recovered: ["RFC-0100"],
        regressed: ["RFC-0101"],
      });
      const entries = Object.fromEntries(result.data!.emitted.map((e) => [e.rfcId, e]));
      expect(entries["RFC-0100"]?.previousOverall).toBe("fail");
      expect(entries["RFC-0101"]?.previousOverall).toBe("pass");
      expect(entries["RFC-0102"]?.previousOverall).toBe("fail");
      const r101Diag = result.data!.diagnostics.find((d) => d.file?.includes("rfc-0101"));
      expect(r101Diag?.message).toContain("regressed: was pass");
      expect(result.summary).toContain("1 regressed, 1 recovered");
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.emit — RFC-1237 AC-6: dry-run", () => {
  test("context.dryRun (the real werkstatt run --dry-run path) writes zero envelopes", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      // The real CLI path: consumeCommonFlags strips --dry-run from argv into
      // context.dryRun — input.flags carries no "dry-run" key at all.
      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot, { dryRun: true }) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.emitted).toHaveLength(1);
      expect(result.summary).toContain("dry-run");
      await expect(fs.stat(envelopePath(workspaceRoot, "RFC-0100"))).rejects.toThrow();
      // The verification dir itself is also not created under dry-run.
      await expect(
        fs.stat(path.join(workspaceRoot, "docs", "rfcs", "verification")),
      ).rejects.toThrow();
    } finally {
      await cleanup();
    }
  });

  test('input.flags["dry-run"] (direct/programmatic callers) writes zero envelopes', async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100", "dry-run": true } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.summary).toContain("dry-run");
      await expect(fs.stat(envelopePath(workspaceRoot, "RFC-0100"))).rejects.toThrow();
    } finally {
      await cleanup();
    }
  });

  test("dry-run still runs probes and reports overall: fail", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: false, detail: "does not exist" });

      const result = await runRfcVerificationEmit(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot, { dryRun: true }) as unknown as ForgeRuntimeContext,
      );

      expect(mockRunProbe).toHaveBeenCalledOnce();
      expect(result.data!.emitted[0]?.overall).toBe("fail");
      expect(result.exitCode).toBe(1);
      await expect(fs.stat(envelopePath(workspaceRoot, "RFC-0100"))).rejects.toThrow();
    } finally {
      await cleanup();
    }
  });
});

describe("verification sweep — --concurrency", () => {
  test("mapWithConcurrency preserves input order and bounds parallelism", async () => {
    let inFlight = 0;
    let maxInFlight = 0;
    const items = Array.from({ length: 10 }, (_, i) => i);
    const results = await mapWithConcurrency(items, 3, async (n) => {
      inFlight += 1;
      maxInFlight = Math.max(maxInFlight, inFlight);
      await new Promise((r) => setTimeout(r, Math.random() * 5));
      inFlight -= 1;
      return n * 2;
    });
    expect(results).toEqual(items.map((n) => n * 2));
    expect(maxInFlight).toBeLessThanOrEqual(3);
    expect(maxInFlight).toBeGreaterThan(1);
  });

  test("resolveConcurrency: absent→1, garbage→1+warn, >16→clamped", () => {
    const warnings: string[] = [];
    const warn = (m: string) => warnings.push(m);
    expect(resolveConcurrency(undefined)).toBe(1);
    expect(resolveConcurrency("abc", warn)).toBe(1);
    expect(resolveConcurrency("0", warn)).toBe(1);
    expect(resolveConcurrency("4", warn)).toBe(4);
    expect(resolveConcurrency("99", warn)).toBe(16);
    expect(warnings).toHaveLength(3);
  });

  test("--concurrency 3 emits identical results to sequential", async () => {
    const ids = ["RFC-0201", "RFC-0202", "RFC-0203", "RFC-0204"];
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: ids.map((id) => ({ id, status: "implemented" })),
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationEmit(
        { flags: { status: "implemented", concurrency: "3" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.emitted.map((e) => e.rfcId)).toEqual(ids);
      expect(result.data!.emitted.every((e) => e.overall === "pass")).toBe(true);
      expect(result.exitCode).toBe(0);
      for (const id of ids) {
        await expect(fs.stat(envelopePath(workspaceRoot, id))).resolves.toBeDefined();
      }
    } finally {
      await cleanup();
    }
  });
});
