// @vitest-environment node
import { test, expect, describe, vi, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { stringify as yamlStringify } from "yaml";

import { runRfcVerificationRefresh } from "./verification-refresh.ts";
import type { ForgeCommandInput, ForgeRuntimeContext } from "../../src/types.ts";

const { mockRunProbe, mockCaptureGitContext, mockGetKernelVersion } = vi.hoisted(() => ({
  mockRunProbe: vi.fn(),
  mockCaptureGitContext: vi.fn(),
  mockGetKernelVersion: vi.fn(),
}));

vi.mock("./acceptance.ts", () => ({
  runProbe: mockRunProbe,
}));

vi.mock("./verification-evidence.ts", async (importOriginal) => {
  const actual = await importOriginal<typeof import("./verification-evidence.ts")>();
  return {
    ...actual,
    captureGitContext: mockCaptureGitContext,
    getKernelVersion: mockGetKernelVersion,
  };
});

const RFC_FRONTMATTER = (id: string, status: string, probes: Record<string, unknown>[] = []) => {
  const probeYaml = probes
    .map(
      (p) =>
        `  - probe: ${p.probe}\n    path: ${p.path ?? ""}\n    criterion: ${p.criterion ?? ""}`,
    )
    .join("\n");
  return `---\nid: ${id}\ntitle: "Test ${id}"\nstatus: ${status}\nkind: command\nscope: workspace\nowners:\n  - architecture\ncreatedAt: 2026-01-01\nupdatedAt: 2026-01-01\nacceptance:\n${probeYaml}\n---\n\n# ${id}\n## Context\nTest.\n`;
};

const PROBE = { probe: "file-exists", path: "src/index.ts", criterion: "AC-1" };

function makeEnvelope(
  rfcId: string,
  emittedAt: string,
  overall: "pass" | "fail" = "pass",
): Record<string, unknown> {
  return {
    rfcId,
    title: `Test ${rfcId}`,
    rfcStatus: "implemented",
    emittedAt,
    commit: "abc123",
    workingTreeDirty: false,
    kernelVersion: "1.0.0",
    rfcFileHash: "hash123",
    acceptanceHash: "accHash123",
    probes: [
      {
        probe: PROBE,
        ok: overall === "pass",
        detail: overall === "pass" ? "exists" : "does not exist",
        durationMs: 5,
      },
    ],
    overall,
  };
}

async function setupWorkspace(opts: {
  rfcs: Array<{ id: string; status: string; probes?: unknown[] }>;
  envelopes?: Array<{ id: string; emittedAt?: string; overall?: "pass" | "fail" }>;
}): Promise<{ workspaceRoot: string; cleanup: () => Promise<void> }> {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "rfc-refresh-test-"));
  const rfcDir = path.join(tmpDir, "docs", "rfcs");
  const verificationDir = path.join(rfcDir, "verification");
  await fs.mkdir(verificationDir, { recursive: true });

  for (const rfc of opts.rfcs) {
    const slug = rfc.id.toLowerCase();
    const probes = rfc.probes ?? [PROBE];
    await fs.writeFile(
      path.join(rfcDir, `${slug}-test.md`),
      RFC_FRONTMATTER(rfc.id, rfc.status, probes),
    );
  }

  for (const env of opts.envelopes ?? []) {
    const slug = env.id.toLowerCase();
    const envelope = makeEnvelope(env.id, env.emittedAt ?? "2026-01-01T00:00:00.000Z", env.overall);
    const header = `# Generated by rfc.verification.emit\n# Do not edit by hand.\n`;
    await fs.writeFile(
      path.join(verificationDir, `${slug}.generated.yaml`),
      header + yamlStringify(envelope) + "\n",
    );
  }

  mockCaptureGitContext.mockResolvedValue({ commit: "abc123", workingTreeDirty: false });
  mockGetKernelVersion.mockResolvedValue("1.0.0");

  return {
    workspaceRoot: tmpDir,
    cleanup: async () => {
      await fs.rm(tmpDir, { recursive: true, force: true });
    },
  };
}

function makeContext(workspaceRoot: string, overrides: Record<string, unknown> = {}) {
  return {
    workspaceRoot,
    logger: { info: () => {} },
    outputFormat: "json" as const,
    commandRegistry: undefined,
    dryRun: false,
    ...overrides,
  };
}

/**
 * RFC-1237: a minimal recording-style WorkspaceIO — writes land in `writes`,
 * never on disk. Lets tests assert which writes the handler attempted through
 * the port without touching fs.
 */
function makeSpyIo() {
  const writes: string[] = [];
  const io = {
    readFile: (p: string) => fs.readFile(p, "utf8"),
    writeFile: async (p: string) => {
      writes.push(p);
    },
    mkdir: async (p: string) => {
      writes.push(`mkdir:${p}`);
    },
    exists: async (p: string) => {
      try {
        await fs.stat(p);
        return true;
      } catch {
        return false;
      }
    },
  };
  return { io, writes };
}

beforeEach(() => {
  mockRunProbe.mockReset();
  mockCaptureGitContext.mockReset();
  mockGetKernelVersion.mockReset();
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe("rfc.verification.refresh — sweep delta report", () => {
  test("reports recovered (fail→pass) and regressed (pass→fail) transitions", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [
        { id: "RFC-0100", status: "implemented" },
        { id: "RFC-0101", status: "implemented" },
        { id: "RFC-0102", status: "implemented" },
      ],
      envelopes: [
        { id: "RFC-0100", overall: "fail" },
        { id: "RFC-0101", overall: "pass" },
        { id: "RFC-0102", overall: "fail" },
      ],
    });

    try {
      // RFC-0100: fail → pass (recovered); RFC-0101: pass → fail (regressed);
      // RFC-0102: fail → fail (still failing — not a regression).
      mockRunProbe
        .mockResolvedValueOnce({ probe: PROBE, ok: true, detail: "exists" })
        .mockResolvedValueOnce({ probe: PROBE, ok: false, detail: "missing" })
        .mockResolvedValueOnce({ probe: PROBE, ok: false, detail: "missing" });

      const result = await runRfcVerificationRefresh(
        { flags: { all: true } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.delta).toEqual({
        recovered: ["RFC-0100"],
        regressed: ["RFC-0101"],
      });
      const entries = Object.fromEntries(result.data!.refreshed.map((r) => [r.rfcId, r]));
      expect(entries["RFC-0100"]?.previousOverall).toBe("fail");
      expect(entries["RFC-0101"]?.previousOverall).toBe("pass");
      expect(entries["RFC-0102"]?.previousOverall).toBe("fail");
      const r101Diag = result.data!.diagnostics.find((d) => d.file?.includes("rfc-0101"));
      expect(r101Diag?.message).toContain("regressed: was pass");
      const r102Diag = result.data!.diagnostics.find((d) => d.file?.includes("rfc-0102"));
      expect(r102Diag?.message).not.toContain("regressed");
      expect(result.summary).toContain("1 regressed, 1 recovered");
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — AC-1: single-RFC refresh", () => {
  test("updates lastRefreshedAt, replaces probes[], preserves emittedAt", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100", emittedAt: "2026-01-01T00:00:00.000Z" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.refreshed).toHaveLength(1);
      expect(result.data!.refreshed[0].rfcId).toBe("RFC-0100");
      expect(result.data!.refreshed[0].overall).toBe("pass");
      expect(result.exitCode).toBe(0);

      // Verify envelope was written with lastRefreshedAt
      const envelopePath = path.join(
        workspaceRoot,
        "docs",
        "rfcs",
        "verification",
        "rfc-0100.generated.yaml",
      );
      const raw = await fs.readFile(envelopePath, "utf-8");
      expect(raw).toContain("lastRefreshedAt");
      expect(raw).toContain("emittedAt: 2026-01-01T00:00:00.000Z");
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — AC-2: --all mode", () => {
  test("iterates over all implemented RFCs with evidence envelopes", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [
        { id: "RFC-0100", status: "implemented" },
        { id: "RFC-0200", status: "implemented" },
        { id: "RFC-0300", status: "accepted" },
      ],
      envelopes: [{ id: "RFC-0100" }, { id: "RFC-0200" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationRefresh(
        { flags: { all: true } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.refreshed).toHaveLength(2);
      expect(result.data!.skipped).toHaveLength(1);
      expect(result.data!.skipped[0].reason).toBe("not implemented");
      expect(result.exitCode).toBe(0);
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — AC-3: probe failure still writes envelope", () => {
  test("writes envelope with overall: fail and exits non-zero", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: false, detail: "does not exist" });

      const result = await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.refreshed).toHaveLength(1);
      expect(result.data!.refreshed[0].overall).toBe("fail");
      expect(result.data!.refreshed[0].probesFailed).toBe(1);
      expect(result.exitCode).toBe(1);

      // Envelope was still written
      const envelopePath = path.join(
        workspaceRoot,
        "docs",
        "rfcs",
        "verification",
        "rfc-0100.generated.yaml",
      );
      const raw = await fs.readFile(envelopePath, "utf-8");
      expect(raw).toContain("overall: fail");
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — AC-4: --dry-run does not write files", () => {
  test("runs probes but does not write envelope files", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100", emittedAt: "2026-01-01T00:00:00.000Z" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100", "dry-run": true } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.refreshed).toHaveLength(1);
      expect(result.data!.refreshed[0].overall).toBe("pass");

      // Envelope file should still have the old content (no lastRefreshedAt)
      const envelopePath = path.join(
        workspaceRoot,
        "docs",
        "rfcs",
        "verification",
        "rfc-0100.generated.yaml",
      );
      const raw = await fs.readFile(envelopePath, "utf-8");
      expect(raw).not.toContain("lastRefreshedAt");
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — RFC-1237 AC-1: context.dryRun (the real CLI path)", () => {
  test("werkstatt run --dry-run consumes --dry-run into context.dryRun — zero writes", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100", emittedAt: "2026-01-01T00:00:00.000Z" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });
      const envelopePath = path.join(
        workspaceRoot,
        "docs",
        "rfcs",
        "verification",
        "rfc-0100.generated.yaml",
      );
      const before = await fs.readFile(envelopePath, "utf-8");

      // The real CLI path: consumeCommonFlags strips --dry-run from argv into
      // context.dryRun — input.flags carries no "dry-run" key at all.
      const result = await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot, { dryRun: true }) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.refreshed).toHaveLength(1);
      expect(await fs.readFile(envelopePath, "utf-8")).toBe(before);
    } finally {
      await cleanup();
    }
  });

  test("recording-IO port sees zero write intents under context.dryRun", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });
      const { io, writes } = makeSpyIo();

      await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot, { dryRun: true, io }) as unknown as ForgeRuntimeContext,
      );

      expect(
        writes,
        "dry-run refresh must issue zero io writes — check the dryRun guard in runRfcVerificationRefresh",
      ).toEqual([]);
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — RFC-1237 AC-2: emit-canonical header", () => {
  test("writes the emit-owned structured marker header, not a refresh-owned one", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      const raw = await fs.readFile(
        path.join(workspaceRoot, "docs", "rfcs", "verification", "rfc-0100.generated.yaml"),
        "utf-8",
      );
      // Structured marker keys — identical-by-construction to what emit writes.
      expect(raw).toMatch(/^generatedMarker: GENERATED\./);
      expect(raw).toContain("ownerCommand: rfc.verification.emit");
      expect(raw).toContain("regenerateCommand: pnpm exec werkstatt run rfc.verification.emit");
      // Refresh never stamps itself as owner — it is a conditional secondary writer.
      expect(raw).not.toContain("rfc.verification.refresh");
    } finally {
      await cleanup();
    }
  });

  test("legacy '#'-comment input header normalizes to the canonical key format", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });
      await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      const raw = await fs.readFile(
        path.join(workspaceRoot, "docs", "rfcs", "verification", "rfc-0100.generated.yaml"),
        "utf-8",
      );
      // setupWorkspace wrote the legacy `# Generated by ...` comment header —
      // refresh output must carry no comment lines at all.
      expect(raw.split("\n").every((line) => !line.startsWith("#"))).toBe(true);
      expect(raw).toMatch(/^generatedMarker: GENERATED\./);
    } finally {
      await cleanup();
    }
  });

  test("writes route through the resolved io port, not ambient fs", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100", emittedAt: "2026-01-01T00:00:00.000Z" }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });
      const { io, writes } = makeSpyIo();
      const envelopePath = path.join(
        workspaceRoot,
        "docs",
        "rfcs",
        "verification",
        "rfc-0100.generated.yaml",
      );

      await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot, { io }) as unknown as ForgeRuntimeContext,
      );

      expect(writes).toEqual([envelopePath]);
      // The spy io never touches disk — the on-disk file keeps its old content.
      const raw = await fs.readFile(envelopePath, "utf-8");
      expect(raw).not.toContain("lastRefreshedAt");
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — AC-5: no evidence envelope", () => {
  test("skips RFC with reason 'no evidence envelope' and exits non-zero", async () => {
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      const result = await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      expect(result.data!.refreshed).toHaveLength(0);
      expect(result.data!.skipped).toHaveLength(1);
      expect(result.data!.skipped[0].reason).toBe("no evidence envelope");
      expect(result.exitCode).toBe(1);
    } finally {
      await cleanup();
    }
  });
});

describe("rfc.verification.refresh — AC-6: emittedAt preservation", () => {
  test("emittedAt is preserved across refreshes", async () => {
    const originalEmittedAt = "2026-01-01T00:00:00.000Z";
    const { workspaceRoot, cleanup } = await setupWorkspace({
      rfcs: [{ id: "RFC-0100", status: "implemented" }],
      envelopes: [{ id: "RFC-0100", emittedAt: originalEmittedAt }],
    });

    try {
      mockRunProbe.mockResolvedValue({ probe: PROBE, ok: true, detail: "exists" });

      await runRfcVerificationRefresh(
        { flags: { id: "RFC-0100" } } as unknown as ForgeCommandInput,
        makeContext(workspaceRoot) as unknown as ForgeRuntimeContext,
      );

      const envelopePath = path.join(
        workspaceRoot,
        "docs",
        "rfcs",
        "verification",
        "rfc-0100.generated.yaml",
      );
      const raw = await fs.readFile(envelopePath, "utf-8");
      expect(raw).toContain(`emittedAt: ${originalEmittedAt}`);
      // lastRefreshedAt should be different (set to now)
      expect(raw).toContain("lastRefreshedAt:");
      // lastRefreshedAt should not equal emittedAt
      expect(raw).not.toMatch(/lastRefreshedAt: 2026-01-01T00:00:00\.000Z/);
    } finally {
      await cleanup();
    }
  });
});
