// Auto-generated type shims for @warpgogol/werkstatt-engine.
// Generated by repo-extract from source exports. Do not edit manually.

declare module "@warpgogol/werkstatt-engine" {
  const _: any;
  export = _;
}

declare module "@warpgogol/werkstatt-engine/os/werkstatt-autonomy-module" {
  export const werkstattAutonomyModule: any;
}

declare module "@warpgogol/werkstatt-engine/os/werkstatt-shared-validate-module" {
  export const werkstattSharedValidateModule: any;
}

declare module "@warpgogol/werkstatt-engine/os/werkstatt-commands-validate-module" {
  export const werkstattCommandsValidateModule: any;
}

declare module "@warpgogol/werkstatt-engine/os/werkstatt-e2e-module" {
  export const werkstattE2eModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel" {
  export function discoverSiteWorkspaces(...args: any[]): any;
  export function loadKernelAppConfig(...args: any[]): any;
  export function loadWorkspaceConfig(...args: any[]): any;
  export function findWorkspaceRoot(...args: any[]): any;
  export function workspacePackageKind(...args: any[]): any;
  export function discoverWorkspacePackages(...args: any[]): any;
  export interface WorkspacePackageInfo {}
  export interface WorkspaceDiscoveryResult {}
  export const parseKernelArgv: any;
  export const resolveCommandFlags: any;
  export const KERNEL_UNIVERSAL_FLAGS: any;
  export const listSiteWorkspaces: any;
  export const listRegisteredKernelCommandNames: any;
  export const listRegisteredKernelCommands: any;
  export const listRegisteredKernelPipelines: any;
  export const loadAppRuntime: any;
  export const executeKernelCommand: any;
  export const executeRegisteredCommand: any;
  export const executeKernelPipeline: any;
  export const buildSchedule: any;
  export const executeScheduledSteps: any;
  export const ScheduledStep: any;
  export const StepExecutionResult: any;
  export const ScheduleError: any;
  export const formatFailureDiagnostics: any;
  export const getOrBuildRegistry: any;
  export const getOrBuildWorkspaceRegistry: any;
  export const clearRegistryCache: any;
  export const setRegistryCacheEnabled: any;
  export const isRegistryCacheEnabled: any;
  export function defineKernelConfig(...args: any[]): any;
  export interface DiscoveredSiteWorkspace {}
  export interface KernelLogEvent {}
  export interface KernelLogger {}
  export interface KernelCommandInput {}
  export interface KernelCommandMetadata {}
  export interface GateConditional {}
  export interface GateMetadata {}
  export interface KernelFlagSpec {}
  export interface KernelRegisteredCommandInfo {}
  export interface KernelNextStep {}
  export interface KernelCommandResult {}
  export interface CheckResult {}
  export interface GeneratedArtifactSpec {}
  export interface GeneratorOwnershipEntry {}
  export interface KernelRuntimeContext {}
  export interface KernelCommandDefinition {}
  export interface KernelPipelineStep {}
  export interface KernelModuleRegistry {}
  export interface KernelModule {}
  export interface KernelAppConfig {}
  export interface KernelExecutionReport {}
  export interface KernelPipelineReport {}
  export interface KernelCommandTiming {}
  export interface PipelineStepTiming {}
  export interface KernelPipelineTimingSummary {}
  export interface ExecuteKernelCommandOptions {}
  export interface ExecuteKernelPipelineOptions {}
  export interface SiteWorkspacesListResult {}
  export type KernelOutputFormat = any;
  export type KernelCommandScope = any;
  export type KernelLogLevel = any;
  export type PipelineLogSeverity = any;
  export type PipelineLogKind = any;
  export type KernelFlagValue = any;
  export type GateSeverity = any;
  export type GatePhase = any;
  export type PipelineStepStatus = any;
  export const forgeAdrModule: any;
  export const runAdrList: any;
  export const runAdrCreate: any;
  export const runAdrValidate: any;
  export const runAdrArchive: any;
  export const ADR_STATUSES: any;
  export const ADR_SCOPES: any;
  export const ADR_DIR: any;
  export const ADR_TEMPLATE_FILE: any;
  export const ADR_ID_PATTERN: any;
  export function createDefaultIO(...args: any[]): any;
  export function createRecordingIO(...args: any[]): any;
  export function createReadOnlyIO(...args: any[]): any;
  export class KernelMetaError { constructor(...args: any[]); }
  export interface ExecOptions {}
  export interface ExecResult {}
  export interface DirEntry {}
  export interface WorkspaceIO {}
  export interface WriteIntent {}
  export function classifyPaths(...args: any[]): any;
  export function deriveImpactedApps(...args: any[]): any;
  export function recommendProfile(...args: any[]): any;
  export function runChangeImpactDerive(...args: any[]): any;
  export const IMPACT_RULES: any;
  export interface ImpactRule {}
  export interface PathClassification {}
  export interface ImpactClassification {}
  export interface ProfileRecommendation {}
  export interface ChangeImpactResult {}
  export type ImpactClass = any;
  export function budgetsFilePath(...args: any[]): any;
  export function appendStepTelemetry(...args: any[]): any;
  export function batchAppendStepTelemetry(...args: any[]): any;
  export function parseTelemetryHistory(...args: any[]): any;
  export function aggregateBudgets(...args: any[]): any;
  export function loadPipelineBudgets(...args: any[]): any;
  export function lookupExpectedDurationMs(...args: any[]): any;
  export function runPipelineBudgetGenerate(...args: any[]): any;
  export function telemetryFileSizeBytes(...args: any[]): any;
  export interface StepTelemetryRecord {}
  export interface StepBudget {}
  export interface PipelineBudgetsFile {}
  export interface PipelineBudgetGenerateResult {}
  export function manifestFilePath(...args: any[]): any;
  export function collectCommandManifestDiagnostics(...args: any[]): any;
  export function buildCommandManifest(...args: any[]): any;
  export function runCommandManifestGenerate(...args: any[]): any;
  export function runCommandManifestValidate(...args: any[]): any;
  export interface CommandManifestEntry {}
  export interface CommandManifest {}
  export const resolveSiteWorkspace: any;
  export const SiteWorkspace: any;
  export const SiteWorkspaceSource: any;
  export const createKernelLogger: any;
  export const KernelRegistry: any;
  export const resolveCompassScanRoot: any;
  export const runKernelWire: any;
  export const iconsModule: any;
  export const runIconsGenerate: any;
  export const runRfcList: any;
  export const runRfcCreate: any;
  export const runRfcValidate: any;
  export const runRfcCommandLifecycleValidate: any;
  export const runRfcCheck: any;
  export const runRfcAcceptanceRun: any;
  export const runProbe: any;
  export const validateAcceptanceShape: any;
  export const runRfcVerificationEmit: any;
  export const buildEvidenceEnvelope: any;
  export const runRfcDnaTraceValidate: any;
  export const runRfcDnaTraceGenerate: any;
  export const buildDnaTrace: any;
  export const collectDecisionLog: any;
  export const scoreDecisions: any;
  export const runRfcDecisionLogGenerate: any;
  export const runRfcSupersedePropose: any;
  export const runRfcArchive: any;
  export const RFC_STATUSES: any;
  export const RFC_KINDS: any;
  export const RFC_SCOPES: any;
  export const RFC_DIR: any;
  export const RFC_TEMPLATE_FILE: any;
  export const RFC_ID_PATTERN: any;
  export const RFC_FULL_REQUIRED_SECTIONS: any;
  export const RFC_METADATA_CUTOFF: any;
  export const createCompassInventoryEntries: any;
  export const CompassInventoryEntry: any;
  export const writeFileAtomic: any;
  export const WriteFileAtomicOptions: any;
  export const writeFileIfChanged: any;
  export const GENERATED_MARKER: any;
  export const EDITABLE_GENERATED_MARKER: any;
  export const hasGeneratedMarker: any;
  export const stripGeneratedMarker: any;
  export const isGeneratedMarkerTextCandidate: any;
  export const buildGeneratedHeader: any;
  export const StripGeneratedMarkerResult: any;
  export const GeneratedHeaderInput: any;
  export const semanticModule: any;
  export const runSemanticPageValidate: any;
  export const runWorkflowLint: any;
  export const runWorkflowList: any;
  export const runWorkflowAmendList: any;
  export const commitMessageModule: any;
  export const runCommitMessageLint: any;
  export const lintCommitSubject: any;
  export const parseGitLogOutput: any;
  export const parseNameOnlyOutput: any;
  export const isExempt: any;
  export const pipelineBudgetModule: any;
  export const validatorInventoryModule: any;
  export const changeImpactModule: any;
  export const commandManifestModule: any;
  export const gitmeshModule: any;
  export const parseSemver: any;
  export const compareSemver: any;
  export const ltSemver: any;
  export const gtSemver: any;
  export const eqSemver: any;
  export const inOpenClosedRange: any;
  export const PLATFORM_SCOPE_PREFIXES: any;
  export const isPlatformScope: any;
  export const hasPlatformScopeFiles: any;
  export const extractTrailer: any;
  export const hasTrailer: any;
  export const resolveMissionDir: any;
  export const resolvePlatformSemanticHash: any;
  export const swimModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/icons" {
  export const iconsModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/adr" {
  export const forgeAdrModule: any;
  export const runAdrList: any;
  export const runAdrCreate: any;
  export const runAdrValidate: any;
  export const runAdrArchive: any;
  export const ADR_STATUSES: any;
  export const ADR_SCOPES: any;
  export const ADR_DIR: any;
  export const ADR_TEMPLATE_FILE: any;
  export const ADR_ID_PATTERN: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/change-impact" {
  export function classifyPaths(...args: any[]): any;
  export function deriveImpactedApps(...args: any[]): any;
  export function recommendProfile(...args: any[]): any;
  export function runChangeImpactDerive(...args: any[]): any;
  export const IMPACT_RULES: any;
  export interface ImpactRule {}
  export interface PathClassification {}
  export interface ImpactClassification {}
  export interface ProfileRecommendation {}
  export interface ChangeImpactResult {}
  export type ImpactClass = any;
}

declare module "@warpgogol/werkstatt-engine/kernel/change-impact-module" {
  export const changeImpactModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/cli" {
  export function main(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/kernel/commit-message" {
  export const commitMessageModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/command-manifest" {
  export function manifestFilePath(...args: any[]): any;
  export function collectCommandManifestDiagnostics(...args: any[]): any;
  export function buildCommandManifest(...args: any[]): any;
  export function runCommandManifestGenerate(...args: any[]): any;
  export function runCommandManifestValidate(...args: any[]): any;
  export interface CommandManifestEntry {}
  export interface CommandManifest {}
}

declare module "@warpgogol/werkstatt-engine/kernel/command-manifest-module" {
  export const commandManifestModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/cache-module" {
  export const cacheModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/discovery" {
  export function discoverSiteWorkspaces(...args: any[]): any;
  export function loadKernelAppConfig(...args: any[]): any;
  export function loadWorkspaceConfig(...args: any[]): any;
  export function findWorkspaceRoot(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/kernel/generated-marker" {
  export function hasGeneratedMarker(...args: any[]): any;
  export function stripGeneratedMarker(...args: any[]): any;
  export function buildGeneratedHeader(...args: any[]): any;
  export function isGeneratedMarkerTextCandidate(...args: any[]): any;
  export const GENERATED_MARKER: any;
  export const EDITABLE_GENERATED_MARKER: any;
  export interface StripGeneratedMarkerResult {}
  export interface GeneratedHeaderInput {}
}

declare module "@warpgogol/werkstatt-engine/kernel/gitmesh-module" {
  export const gitmeshModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/swim-module" {
  export const swimModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/pipeline-budget" {
  export const pipelineBudgetModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/pipeline-budgets" {
  export function budgetsFilePath(...args: any[]): any;
  export function appendStepTelemetry(...args: any[]): any;
  export function batchAppendStepTelemetry(...args: any[]): any;
  export function parseTelemetryHistory(...args: any[]): any;
  export function aggregateBudgets(...args: any[]): any;
  export function loadPipelineBudgets(...args: any[]): any;
  export function lookupExpectedDurationMs(...args: any[]): any;
  export function runPipelineBudgetGenerate(...args: any[]): any;
  export function telemetryFileSizeBytes(...args: any[]): any;
  export interface StepTelemetryRecord {}
  export interface StepBudget {}
  export interface PipelineBudgetsFile {}
  export interface PipelineBudgetGenerateResult {}
}

declare module "@warpgogol/werkstatt-engine/kernel/validator-inventory" {
  export const validatorInventoryModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/semantic" {
  export const semanticModule: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/runtime" {
  export const parseKernelArgv: any;
  export const resolveCommandFlags: any;
  export const KERNEL_UNIVERSAL_FLAGS: any;
  export const listSiteWorkspaces: any;
  export const listRegisteredKernelCommandNames: any;
  export const listRegisteredKernelCommands: any;
  export const listRegisteredKernelPipelines: any;
  export const loadAppRuntime: any;
  export const executeKernelCommand: any;
  export const executeRegisteredCommand: any;
  export const executeKernelPipeline: any;
  export const buildSchedule: any;
  export const executeScheduledSteps: any;
  export const ScheduledStep: any;
  export const StepExecutionResult: any;
  export const ScheduleError: any;
  export const formatFailureDiagnostics: any;
  export const getOrBuildRegistry: any;
  export const getOrBuildWorkspaceRegistry: any;
  export const clearRegistryCache: any;
  export const setRegistryCacheEnabled: any;
  export const isRegistryCacheEnabled: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/types" {
  export function defineKernelConfig(...args: any[]): any;
  export interface DiscoveredSiteWorkspace {}
  export interface KernelLogEvent {}
  export interface KernelLogger {}
  export interface KernelCommandInput {}
  export interface KernelCommandMetadata {}
  export interface GateConditional {}
  export interface GateMetadata {}
  export interface KernelFlagSpec {}
  export interface KernelRegisteredCommandInfo {}
  export interface KernelNextStep {}
  export interface KernelCommandResult {}
  export interface CheckResult {}
  export interface GeneratedArtifactSpec {}
  export interface GeneratorOwnershipEntry {}
  export interface KernelRuntimeContext {}
  export interface KernelCommandDefinition {}
  export interface KernelPipelineStep {}
  export interface KernelModuleRegistry {}
  export interface KernelModule {}
  export interface KernelAppConfig {}
  export interface KernelExecutionReport {}
  export interface KernelPipelineReport {}
  export interface KernelCommandTiming {}
  export interface PipelineStepTiming {}
  export interface KernelPipelineTimingSummary {}
  export interface ExecuteKernelCommandOptions {}
  export interface ExecuteKernelPipelineOptions {}
  export interface SiteWorkspacesListResult {}
  export type KernelOutputFormat = any;
  export type KernelCommandScope = any;
  export type KernelLogLevel = any;
  export type PipelineLogSeverity = any;
  export type PipelineLogKind = any;
  export type KernelFlagValue = any;
  export type GateSeverity = any;
  export type GatePhase = any;
  export type PipelineStepStatus = any;
}

declare module "@warpgogol/werkstatt-engine/kernel/workspace-discovery" {
  export function workspacePackageKind(...args: any[]): any;
  export function discoverWorkspacePackages(...args: any[]): any;
  export interface WorkspacePackageInfo {}
  export interface WorkspaceDiscoveryResult {}
}

declare module "@warpgogol/werkstatt-engine/kernel/workspace-io" {
  export function createDefaultIO(...args: any[]): any;
  export function createRecordingIO(...args: any[]): any;
  export function createReadOnlyIO(...args: any[]): any;
  export class KernelMetaError { constructor(...args: any[]); }
  export interface ExecOptions {}
  export interface ExecResult {}
  export interface DirEntry {}
  export interface WorkspaceIO {}
  export interface WriteIntent {}
}

declare module "@warpgogol/werkstatt-engine/kernel/workflow" {
  export const runWorkflowLint: any;
  export const runWorkflowList: any;
  export const runWorkflowAmendList: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/dht" {
  export const dhtSiteEntrySchema: any;
  export const dhtConfigSchema: any;
  export const dhtLookupResultSchema: any;
  export const dhtPlacementReasonSchema: any;
  export const workshopCapacitySchema: any;
  export const dhtPlacementResultSchema: any;
  export const dhtCacheEntrySchema: any;
}

declare module "@warpgogol/werkstatt-engine/kernel/dht-module" {
  export const dhtModule: any;
}

declare module "@warpgogol/werkstatt-engine/mission" {
  export const runMissionOpen: any;
  export const MissionOpenData: any;
  export const runMissionStatus: any;
  export const MissionStatusData: any;
  export const runMissionClose: any;
  export const MissionCloseData: any;
  export const runMissionAbort: any;
  export const MissionAbortData: any;
  export const runMissionList: any;
  export const MissionListData: any;
  export const runMissionMaterialize: any;
  export const MissionMaterializeData: any;
  export const runMissionMaterializeInternal: any;
  export const MissionMaterializeInternalOptions: any;
  export const runMissionValidate: any;
  export const MissionValidateData: any;
  export const runMissionBuild: any;
  export const MissionBuildData: any;
  export const runMissionDiff: any;
  export const MissionDiffData: any;
  export const runMissionReconcile: any;
  export const MissionReconcileData: any;
  export const runMissionPreview: any;
  export const MissionPreviewData: any;
  export const runMissionGitCommit: any;
  export const MissionGitCommitData: any;
  export const isWorkpieceDirty: any;
  export const WorkpieceDirtyResult: any;
  export const investigateUntrackedFiles: any;
  export const UntrackedFileReport: any;
  export const cacheCloneCommit: any;
  export const runMissionCleanup: any;
  export const MissionCleanupData: any;
  export const runValidatePostbuild: any;
  export const ValidatePostbuildData: any;
  export const ValidatePostbuildStepResult: any;
  export const resolveActorFromEnv: any;
  export const resolveActor: any;
  export const ActorIdentity: any;
  export const createSignedCommit: any;
  export const SignedCommitResult: any;
  export const resolveMissionEvidenceDir: any;
  export const resolveMissionDir: any;
  export const persistEnvFilesToCacheClone: any;
  export const restoreEnvFilesFromCacheClone: any;
  export const collectEnvFiles: any;
  export const EnvPersistResult: any;
  export const OPERATOR_CONFIG_FILES: any;
  export const persistOperatorConfigFiles: any;
  export const restoreOperatorConfigFiles: any;
  export const OperatorConfigPersistResult: any;
  export const runMaterializeConfigValidate: any;
  export const runWorkpieceConfigPresenceCheck: any;
  export const WorkpieceConfigPresenceResult: any;
  export const runMissionResume: any;
  export const MissionResumeData: any;
  export const runMissionJournalShow: any;
  export const MissionJournalShowData: any;
  export const runMissionPreflight: any;
  export const MissionPreflightInput: any;
  export const PreflightCheckResult: any;
  export const MissionPreflightData: any;
}

declare module "@warpgogol/werkstatt-engine/sternsystem" {
  export const runSternsystemRegister: any;
  export const SternsystemRegisterData: any;
  export const runSternsystemList: any;
  export const SternsystemListData: any;
  export const runSternsystemValidate: any;
  export const SternsystemValidateData: any;
  export const runSternsystemPin: any;
  export const SternsystemPinData: any;
  export const runSternsystemExtract: any;
  export const SternsystemExtractData: any;
  export const runSternsystemSync: any;
  export const SternsystemSyncData: any;
  export const runSternsystemStatus: any;
  export const SternsystemStatusData: any;
  export const runSternsystemDiscover: any;
  export const SternsystemDiscoverData: any;
  export const runSternsystemPassportGenerate: any;
  export const SternsystemPassportGenerateData: any;
  export const runSternsystemPassportVerify: any;
  export const SternsystemPassportVerifyData: any;
  export const runSternsystemHandoverPrepare: any;
  export const SternsystemHandoverPrepareData: any;
  export const runSternsystemHandoverComplete: any;
  export const SternsystemHandoverCompleteData: any;
  export const runSternsystemHandoverCancel: any;
  export const SternsystemHandoverCancelData: any;
  export const buildPassportPayload: any;
  export const signPassport: any;
  export const verifyPassport: any;
  export const derivePublicKey: any;
  export const computePassportHash: any;
  export const SitePassportV1: any;
  export const SignedSitePassport: any;
  export const computeAuthorizationHash: any;
  export const signAuthorization: any;
  export const verifyAuthorization: any;
  export const resolveAuthorizationPath: any;
  export const readAuthorization: any;
  export const writeAuthorization: any;
  export const removeAuthorization: any;
  export const isAuthorizationExpired: any;
  export const HandoverAuthorizationV1: any;
  export const SignedHandoverAuthorization: any;
  export const HandoverCompleteResult: any;
  export const HandoverEventMetadata: any;
  export const resolveCacheClonePath: any;
  export const resolveWorkpiecePath: any;
  export const readSystemConfig: any;
  export const readSystemConfigFromWorkpiece: any;
  export const writeSystemConfig: any;
  export const readSystemState: any;
  export const readSystemStateFromWorkpiece: any;
  export const writeSystemState: any;
  export const writeSystemStateToWorkpiece: any;
  export const readSystemConfigSmart: any;
  export const readSystemStateSmart: any;
  export const writeSystemStateSmart: any;
  export const writeSystemConfigSmart: any;
  export const discoverSystems: any;
  export const DiscoveryResult: any;
  export const readServicesRegistry: any;
  export const findServiceEntry: any;
  export const hasAppsCollision: any;
  export const MirrorProtocol: any;
  export const inferMirrorProtocol: any;
  export const isGitAccessible: any;
  export const resolveMirrorPath: any;
  export const MirrorResolution: any;
  export const resolveMirrors: any;
  export const readPassport: any;
  export const writePassport: any;
  export const resolvePassportPath: any;
}

declare module "@warpgogol/werkstatt-engine/bordbuch" {
  export const runBordbuchAppend: any;
  export const BordbuchAppendData: any;
  export const runBordbuchValidate: any;
  export const BordbuchValidateData: any;
  export const runBordbuchStatus: any;
  export const BordbuchStatusData: any;
  export const runBordbuchGenerate: any;
  export const runBordbuchRepair: any;
  export const BordbuchRepairResult: any;
  export const BordbuchRepairOrphan: any;
  export const runBordbuchCommit: any;
  export const commitBordbuchProjections: any;
  export const BordbuchCommitResult: any;
  export const appendBordbuchEntry: any;
  export const readBordbuch: any;
  export const resolveBordbuchPath: any;
  export const resolveBordbuchProjectionDir: any;
  export const validateWriterRole: any;
  export const computeEntryHash: any;
  export const DEPRECATED_KIND_MIGRATIONS: any;
  export const migrateDeprecatedKind: any;
  export const BordbuchViolation: any;
  export const CommitAndPushResult: any;
  export const appendAndCommitBordbuch: any;
  export const appendBatchAndCommitBordbuch: any;
  export const AppendAndCommitResult: any;
  export const AppendBatchAndCommitResult: any;
  export const AppendBordbuchOptions: any;
  export const BatchBordbuchEntrySpec: any;
  export const createBordbuchModule: any;
}

declare module "@warpgogol/werkstatt-engine/artifact-store" {
  export function createArtifactStoreModule(...args: any[]): any;
  export const runArtifactStorePut: any;
  export const ArtifactStorePutData: any;
  export const storeArtifactCore: any;
  export const StoreArtifactCoreResult: any;
  export const runArtifactStoreGet: any;
  export const ArtifactStoreGetData: any;
  export const runArtifactStoreValidate: any;
  export const ArtifactStoreValidateData: any;
  export const runArtifactStoreGc: any;
  export const ArtifactStoreGcData: any;
  export const artifactStorePreflight: any;
  export const ArtifactPreflightResult: any;
  export const artifactStoreRehydrate: any;
}

declare module "@warpgogol/werkstatt-engine/behavior-snapshot" {
  export function createBehaviorSnapshotModule(...args: any[]): any;
  export const runBehaviorSnapshotCapture: any;
  export const BehaviorSnapshotCaptureData: any;
  export const runBehaviorSnapshotDiff: any;
  export const BehaviorSnapshotDiffData: any;
}

declare module "@warpgogol/werkstatt-engine/release" {
  export function createReleaseModule(...args: any[]): any;
  export const runReleasePrepare: any;
  export const ReleasePrepareData: any;
  export const runReleaseReady: any;
  export const ReleaseReadyData: any;
  export const runReleaseValidate: any;
  export const ReleaseValidateData: any;
  export const runReleaseList: any;
  export const ReleaseListData: any;
  export const runReleaseStateValidate: any;
  export const ReleaseStateValidateData: any;
  export const ReleaseStateCheck: any;
  export const runBootSmokeCommand: any;
  export const BootSmokeCommandData: any;
  export const runBootSmoke: any;
  export const BootSmokeResult: any;
  export const BootSmokeRequestSpec: any;
  export const BootSmokeRequestResult: any;
  export const planBootSmokeRequests: any;
  export const detectBootSmokeLanguages: any;
  export const resolveWranglerConfig: any;
  export const resolveLanguages: any;
  export const WranglerResolution: any;
  export const simulateBindings: any;
}

declare module "@warpgogol/werkstatt-engine/leitstand" {
  export const runLeitstandDevDeploy: any;
  export const DevDeployResult: any;
  export const runLeitstandPropagate: any;
  export const LeitstandPropagateData: any;
  export const runLeitstandPromote: any;
  export const LeitstandPromoteData: any;
  export const runLeitstandStatus: any;
  export const LeitstandStatusData: any;
  export const runLeitstandRollback: any;
  export const LeitstandRollbackData: any;
  export const runLeitstandHealth: any;
  export const LeitstandHealthData: any;
  export const runLeitstandPipelineCheck: any;
  export const PipelineCheckResult: any;
  export const runLeitstandHotfixDevDeploy: any;
  export const HotfixDevDeployResult: any;
  export const runLeitstandCertify: any;
  export const CertifyInput: any;
  export const CertifyResult: any;
  export const executeDeployPhases: any;
  export const DeployExecutionContext: any;
  export const DeployExecutionResult: any;
  export const runLeitstandServiceDevDeploy: any;
  export const runLeitstandServicePromote: any;
  export const createLeitstandModule: any;
}

declare module "@warpgogol/werkstatt-engine/leitstand/adapters/cloudflare-workers" {
  export function filterEnv(...args: any[]): any;
  export function sourceDotenv(...args: any[]): any;
  export function readBehaviorSnapshot(...args: any[]): any;
  export function verifyRedirectRoute(...args: any[]): any;
  export function createCloudflareWorkersAdapter(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/notausgang" {
  export function createNotausgangModule(...args: any[]): any;
  export const runNotausgangExport: any;
  export const NotausgangExportData: any;
  export const runNotausgangValidate: any;
  export const NotausgangValidateData: any;
  export const CheckStatus: any;
  export const NotausgangViolation: any;
}

declare module "@warpgogol/werkstatt-engine/evidence" {
  export const createEvidenceModule: any;
  export const runEvidenceSync: any;
  export const EvidenceSyncResult: any;
  export const runEvidenceFetch: any;
  export const EvidenceFetchResult: any;
  export const EvidenceListResult: any;
  export const createR2Client: any;
  export const resolveR2ConfigFromEnv: any;
  export const MissingEnvError: any;
  export const R2ClientConfig: any;
  export const R2PutObjectInput: any;
  export const R2GetObjectOutput: any;
  export const R2ListObject: any;
}

declare module "@warpgogol/werkstatt-engine/handoff" {
  export function createHandoffModule(...args: any[]): any;
  export const diffCapabilities: any;
  export const intentMatches: any;
  export const worstTier: any;
  export const hashFile: any;
  export const readLock: any;
  export const readManifest: any;
  export const readRegistryView: any;
  export const resolveCurrentEcosystem: any;
  export const resolvePlatformSemanticHash: any;
  export const sha256OfBytes: any;
  export const CurrentEcosystem: any;
  export const runHandoffValidate: any;
  export const HandoffValidateData: any;
  export const runHandoffPack: any;
  export const HandoffPackData: any;
  export const runHandoffAbsorb: any;
  export const HandoffAbsorbData: any;
  export const buildCatchupReport: any;
  export const BuildReportInput: any;
  export const runMigratorRegistryValidate: any;
  export const MigratorRegistryValidateData: any;
  export const migratorRegistry: any;
  export const migratorsToApply: any;
  export const numericRfcId: any;
  export const allMigratorIds: any;
  export const MigrationError: any;
  export const compareSemver: any;
  export const eqSemver: any;
  export const gtSemver: any;
  export const inOpenClosedRange: any;
  export const ltSemver: any;
  export const parseSemver: any;
  export const compareEcosystem: any;
  export const CompareEcosystemInput: any;
  export const PLATFORM_SCOPE_PREFIXES: any;
  export const isPlatformScope: any;
  export const hasPlatformScopeFiles: any;
  export const extractTrailer: any;
  export const hasTrailer: any;
  export const runWerkstattLockStatus: any;
  export const WerkstattLockStatusData: any;
  export const runWerkstattLockRecover: any;
  export const WerkstattLockRecoverData: any;
  export const acquireLock: any;
  export const releaseLock: any;
  export const heartbeatLock: any;
  export const readAllLocks: any;
  export const isLockStale: any;
  export const startOperation: any;
  export const completeOperation: any;
  export const failOperation: any;
  export const readOperation: any;
  export const computeInputHash: any;
  export const generateOperationId: any;
  export const atomicWriteFile: any;
  export const atomicMoveDir: any;
  export const resolveStagingDir: any;
  export const createMissionModule: any;
  export const runWorkpieceRead: any;
  export const runWorkpieceWrite: any;
  export const isClientEditable: any;
  export const WorkpieceReadResult: any;
  export const WorkpieceWriteResult: any;
  export const createBordbuchModule: any;
  export const createNachweisModule: any;
  export const appendBordbuchEntry: any;
  export const readBordbuch: any;
  export const runBordbuchGenerate: any;
  export const runBordbuchStatus: any;
  export const BordbuchViolation: any;
  export const createArtifactStoreModule: any;
  export const createBehaviorSnapshotModule: any;
  export const createReleaseModule: any;
  export const createLeitstandModule: any;
  export const createSubdomainModule: any;
  export const createCustomdomainModule: any;
  export const createDnsModule: any;
  export const createNotausgangModule: any;
  export const createDeployModule: any;
  export const createEvidenceModule: any;
  export const createPlatformModule: any;
  export const runPlatformConsistencyValidate: any;
  export const PlatformConsistencyData: any;
  export const PlatformConsistencyViolation: any;
}

declare module "@warpgogol/werkstatt-engine/handoff-module" {
  export function createHandoffModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/mission-module" {
  export function createMissionModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/sternsystem-module" {
  export function createSternsystemModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/bordbuch-module" {
  export function createBordbuchModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/artifact-store-module" {
  export function createArtifactStoreModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/behavior-snapshot-module" {
  export function createBehaviorSnapshotModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/release-module" {
  export function createReleaseModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/leitstand-module" {
  export function createLeitstandModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/fleet" {
  export const runFleetSitesGenerate: any;
  export const validateFleetSitesDrift: any;
  export const FleetSiteRecord: any;
  export const runFleetApply: any;
  export const FleetApplyResult: any;
  export const FleetApplyReportEntry: any;
  export const registerOwnership: any;
  export const verifyOwnership: any;
  export const transferOwnership: any;
  export const deriveInstanceId: any;
  export const OwnershipError: any;
  export const OwnershipClaim: any;
  export const RegisterResult: any;
  export const VerifyResult: any;
  export const TransferResult: any;
  export const createFleetModule: any;
}

declare module "@warpgogol/werkstatt-engine/fleet-module" {
  export function createFleetModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/subdomain-module" {
  export function createSubdomainModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/customdomain-module" {
  export function createCustomdomainModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/dns-module" {
  export function createDnsModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/notausgang-module" {
  export function createNotausgangModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/deploy-module" {
  export function createDeployModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/platform-module" {
  export function createPlatformModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/identity-module" {
  export function createIdentityModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/evidence-module" {
  export function createEvidenceModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/nachweis-module" {
  export function createNachweisModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/sichtpass-module" {
  export function createSichtpassModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/signing" {
  export const generateKeyPair: any;
  export const getPublicKey: any;
  export const loadPrivateKey: any;
  export const loadPublicKey: any;
  export const saveKeyPair: any;
  export const toHex: any;
  export const fromHex: any;
  export const toPem: any;
  export const fromPem: any;
  export const privateKeyPemToBytes: any;
  export const publicKeyPemToBytes: any;
  export const keyExists: any;
  export const canonicalBytes: any;
  export const signBytes: any;
  export const verifyBytes: any;
  export const sign: any;
  export const verify: any;
}

declare module "@warpgogol/werkstatt-engine/signing-module" {
  export function createSigningModule(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/integrity" {
  export const runInit: any;
  export const runUpdate: any;
  export const runVerify: any;
  export const runRecordBuild: any;
  export const runBackfillRevisions: any;
  export const generateSigningKeyPairPemAsync: any;
  export const signJsonPayloadAsync: any;
  export const signLatestBuildArtifacts: any;
  export const signBuildIdentity: any;
  export const writeReleasePublicKey: any;
  export const verifyBuildIdentitySignature: any;
  export const loadSignedManifest: any;
  export const loadPublicKeyPem: any;
  export const verifyManifestSignature: any;
  export const verifyJsonSignatureAsync: any;
  export const compareManifestWithLocalArtifacts: any;
  export const requireEnv: any;
  export const optionalEnv: any;
  export const buildLatestDir: any;
  export const signedManifestPath: any;
  export const ensureDir: any;
  export const writeText: any;
  export const runIntegrityInit: any;
  export const runIntegrityUpdate: any;
  export const runIntegrityVerify: any;
  export const runIntegrityBuildRecord: any;
  export const runIntegritySign: any;
  export const runIntegrityVerifyRelease: any;
  export const runIntegrityGenerateSigningKeypair: any;
  export const runIntegrityBackfillRevisions: any;
  export const STANDARD_INTEGRITY_PIPELINE: any;
  export const getRevisionByPath: any;
  export const RevisionByPathResult: any;
}

declare module "@warpgogol/werkstatt-engine/observability" {
  export const observabilityModule: any;
  export const runObservabilityConventionsValidate: any;
  export const runObservabilityStackValidate: any;
  export const runObservabilityStackHealth: any;
  export const runObservabilityWorkersValidate: any;
  export const runObservabilityFactorySmoke: any;
  export const runFleetProbeTargetsGenerate: any;
  export const runFleetProbeValidate: any;
  export const runObservabilityAlertsGenerate: any;
  export const runObservabilityAlertsValidate: any;
  export const runObservabilityAlertsApply: any;
  export const runObservabilityDeliveryValidate: any;
  export const runObservabilityMcpValidate: any;
  export const ALERT_RULES: any;
  export const NOTIFICATION_CHANNELS: any;
}

declare module "@warpgogol/werkstatt-engine/observability/module" {
  export const observabilityModule: any;
}

declare module "@warpgogol/werkstatt-engine/fingerprint" {
  export const byteHash: any;
  export const byteHashFile: any;
  export const stableStringify: any;
  export const stableJsonHash: any;
  export const isSha256Digest: any;
  export const CANONICAL_JSON_V1: any;
  export const snapshotCanonicalJsonObjectV1: any;
  export const isCanonicalJsonObjectV1: any;
  export const canonicalJsonBytesV1: any;
  export const canonicalJsonHashV1: any;
  export const CanonicalJsonInvariantError: any;
  export const hashHtml: any;
}

declare module "@warpgogol/werkstatt-engine/fingerprint/semantic" {
  export const fingerprintFile: any;
  export const fingerprintTree: any;
}

declare module "@warpgogol/werkstatt-engine/agent-gate" {
  export function __resetLimiterCache(...args: any[]): any;
  export function createAgentGate(...args: any[]): any;
  export interface AgentGate {}
  export function validateAgainstCapabilitySchema(...args: any[]): any;
  export function buildIntegrationEventFromAction(...args: any[]): any;
  export interface ValidationFieldError {}
  export type ValidationOutcome = any;
  export function isJsonRpcRequest(...args: any[]): any;
  export function jsonRpcError(...args: any[]): any;
  export function jsonRpcSuccess(...args: any[]): any;
  export const PINNED_MCP_PROTOCOL_VERSION: any;
  export const JSON_RPC_ERROR: any;
  export interface JsonRpcRequest {}
  export interface JsonRpcSuccess {}
  export interface JsonRpcErrorBody {}
  export interface JsonRpcError {}
  export type JsonRpcId = any;
  export type JsonRpcResponse = any;
  export function buildToolsList(...args: any[]): any;
  export interface McpTool {}
  export function createFixedWindowLimiter(...args: any[]): any;
  export interface RateLimitResult {}
  export interface RateLimiter {}
}

declare module "@warpgogol/werkstatt-engine/agent-gate/astro" {
  export function createAgentMcpRoute(...args: any[]): any;
  export function createAgentActionRoute(...args: any[]): any;
  export function createAgentSearchRoute(...args: any[]): any;
}

declare module "@warpgogol/werkstatt-engine/changelog" {
  export const runChangelogGenerate: any;
  export const runChangelogRebuildIndex: any;
  export const runChangelogBackfill: any;
}

declare module "@warpgogol/werkstatt-engine/schemas" {
  export const handoffCapabilitySchema: any;
  export const handoffEcosystemSchema: any;
  export const handoffBuildSchema: any;
  export const handoffLockSchema: any;
  export const handoffManifestEntrySchema: any;
  export const handoffManifestSchema: any;
  export const systemPinSchema: any;
  export const mirrorStorageTypeSchema: any;
  export const mirrorEntrySchema: any;
  export const serviceSubdomainSchema: any;
  export const serviceEntrySchema: any;
  export const systemConfigSchema: any;
  export const systemStateSchema: any;
  export const servicesRegistrySchema: any;
  export const werkstattLockSchema: any;
  export const werkstattOperationRecordSchema: any;
  export const missionStateSchema: any;
  export const missionManifestSchema: any;
  export const bordbuchEntryKindSchema: any;
  export const bordbuchEntryStatusSchema: any;
  export const bordbuchEntrySchema: any;
  export const STERNSYSTEM_ID_REGEX: any;
  export const MISSION_ID_REGEX: any;
  export const RELEASE_ID_REGEX: any;
  export const BORDBUCH_EVENT_ID_REGEX: any;
  export const NON_ASCII_REGEX: any;
  export const STERNSYSTEM_ID_POLICY: any;
  export const MISSION_ID_POLICY: any;
  export const RELEASE_ID_POLICY: any;
  export const BORDBUCH_EVENT_ID_POLICY: any;
  export const isLatinOnly: any;
  export const materializationReportSchema: any;
  export const validationReportSchema: any;
  export const authoredDiffSchema: any;
  export const releaseArtifactManifestSchema: any;
  export const releaseArtifactRefSchema: any;
  export const releaseArtifactStateSchema: any;
  export const releaseStateSchema: any;
  export const legacyReleaseStateSchema: any;
  export const legacyReleaseDiagnosticSchema: any;
  export const releaseManifestSchema: any;
  export const behaviorSnapshotDifferenceSchema: any;
  export const behaviorSnapshotDiffSchema: any;
  export const buildIdentitySchema: any;
  export const deploymentAdapterNameSchema: any;
  export const deploymentChannelSchema: any;
  export const lastPropagatedChannelSchema: any;
  export const purgeResultSchema: any;
  export const deploymentStaticConfigSchema: any;
  export const healthCheckSchema: any;
  export const propagationResultSchema: any;
  export const routeFactSchema: any;
  export const integrationSecretLocationSchema: any;
  export const integrationManifestSchema: any;
  export const integrationNullingSchema: any;
  export const notausgangManifestSchema: any;
  export const diagnosticSeveritySchema: any;
  export const diagnosticEvidenceSchema: any;
  export const diagnosticSchema: any;
  export const diagnosticRuleIdSchema: any;
  export const safeWorkspaceRelativePathSchema: any;
  export const safeDiagnosticUrlSchema: any;
  export const DIAGNOSTIC_LIMITS: any;
  export const dhtSiteEntrySchema: any;
  export const dhtConfigSchema: any;
  export const dhtLookupResultSchema: any;
  export const dhtPlacementReasonSchema: any;
  export const workshopCapacitySchema: any;
  export const dhtPlacementResultSchema: any;
  export const dhtCacheEntrySchema: any;
}

declare module "@warpgogol/werkstatt-engine/component" {
  export const parseComponentManifestV1: any;
  export const parseResolvedComponentSetV1: any;
  export const componentManifestV1Schema: any;
  export const resolvedComponentSetV1Schema: any;
  export const computeManifestHash: any;
  export const computeSetHash: any;
  export const verifySetHash: any;
  export const verifySetHashStrict: any;
  export const computeDependencyGraphHash: any;
  export const computeGrantSetHash: any;
  export const computeEffectPolicyHash: any;
  export const computeIsolationPolicyHash: any;
}

declare module "@warpgogol/werkstatt-engine/testing/smoke" {
  const _: any;
  export = _;
}

declare module "@warpgogol/werkstatt-engine/testing/integration" {
  const _: any;
  export = _;
}

declare module "@warpgogol/werkstatt-engine/testing/e2e" {
  const _: any;
  export = _;
}

declare module "@warpgogol/werkstatt-engine/e2e" {
  export const runColdE2e: any;
}

declare module "@warpgogol/werkstatt-engine/component-runtime/reflection" {
  export function toReflectedState(...args: any[]): any;
  export function createCapabilityCatalog(...args: any[]): any;
  export function assertNoForbiddenFields(...args: any[]): any;
  export interface CapabilityCatalogEntryV1 {}
  export interface CapabilityCatalogV1 {}
  export interface LiveComponentObservation {}
  export interface ReflectionInput {}
  export type ReflectedLifecycleState = any;
}

declare module "@warpgogol/werkstatt-engine/component-runtime/conformance" {
  export function createConformanceResult(...args: any[]): any;
  export interface ConformanceEventV1 {}
  export interface ConformanceExpectationV1 {}
  export interface ConformanceScenarioV1 {}
  export interface ConformanceTraceEntryV1 {}
  export interface ConformanceMismatchV1 {}
  export interface ConformanceCleanupReportV1 {}
  export interface ConformanceResultV1 {}
  export type ConformanceEventType = any;
  export type ConformanceExpectationKind = any;
}

declare module "@warpgogol/werkstatt-engine/component-runtime/testing" {
  export function runConformanceScenario(...args: any[]): any;
  export function buildCatalog(...args: any[]): any;
  export interface TrustedFixture {}
  export interface HarnessOptions {}
  export const TEST_MODE_SENTINEL: any;
}

declare module "@warpgogol/werkstatt-engine/isolation/contracts" {
  export const REJECTED_ADAPTER_TIERS: any;
  export const REQUIRED_PROPERTIES: any;
  export interface IsolationPropertyEvidenceV1 {}
  export interface AttenuatedGrantV1 {}
  export interface AttenuatedGrantSetV1 {}
  export interface WorkloadLimitsV1 {}
  export interface CapabilityBridgeRequestV1 {}
  export interface CapabilityBridgeResponseV1 {}
  export interface TerminationReportV1 {}
  export interface SandboxedWorkloadCreateV1 {}
  export interface SandboxedWorkloadV1 {}
  export interface IsolationAdapterV1 {}
  export interface AdversarialCaseResultV1 {}
  export interface IsolationConformanceResultV1 {}
  export type IsolationPropertyKind = any;
  export type IsolationConformanceStatus = any;
  export type AdversarialCaseKind = any;
}

declare module "@warpgogol/werkstatt-engine/isolation/schemas" {
  export function validateIsolationAdapter(...args: any[]): any;
  export function validateBridgeRequest(...args: any[]): any;
  export const isolationPropertyEvidenceV1Schema: any;
  export const attenuatedGrantV1Schema: any;
  export const attenuatedGrantSetV1Schema: any;
  export const workloadLimitsV1Schema: any;
  export const capabilityBridgeRequestV1Schema: any;
  export const capabilityBridgeResponseV1Schema: any;
  export const terminationReportV1Schema: any;
  export const sandboxedWorkloadCreateV1Schema: any;
  export const adversarialCaseResultV1Schema: any;
  export const isolationConformanceResultV1Schema: any;
  export const isolationAdapterV1Schema: any;
  export type IsolationContractViolation = any;
}

declare module "@warpgogol/werkstatt-engine/isolation/conformance" {
  export function runIsolationConformance(...args: any[]): any;
  export function createConformanceResult(...args: any[]): any;
  export interface IsolationConformanceFixtureV1 {}
  export interface IsolationConformanceOptions {}
}

declare module "@warpgogol/werkstatt-engine/certification" {
  export const digestSchema: any;
  export const schemaIdSchema: any;
  export const candidateIdSchema: any;
  export const evidenceIdSchema: any;
  export const decisionIdSchema: any;
  export const actionIdSchema: any;
  export const eventIdSchema: any;
  export const operationIdSchema: any;
  export const attemptIdSchema: any;
  export const authoritySequenceSchema: any;
  export const humanReadableIdSchema: any;
  export const utcTimestampSchema: any;
  export const gateChannelSchema: any;
  export const environmentSchema: any;
  export const certificationStatusSchema: any;
  export const safeSemanticPathSchema: any;
  export const safeLocatorSchema: any;
  export const buildConfigV1Schema: any;
  export const deploymentPlanV1Schema: any;
  export const observedEnvironmentV1Schema: any;
  export const releaseCandidateV1Schema: any;
  export const producerManifestV1Schema: any;
  export const rubricManifestV1Schema: any;
  export const toolchainManifestV1Schema: any;
  export const issuerManifestV1Schema: any;
  export const resolvedRequirementV1Schema: any;
  export const certificationPolicyBundleV1Schema: any;
  export const payloadDescriptorV1Schema: any;
  export const redactionReportV1Schema: any;
  export const attestationStatementV1Schema: any;
  export const authorityAdmissionV1Schema: any;
  export const evidenceResultV1Schema: any;
  export const evidenceEnvelopeV1Schema: any;
  export const dossierEventKindSchema: any;
  export const dossierEventV1Schema: any;
  export const dossierManifestProjectionV1Schema: any;
  export const dossierIncidentV1Schema: any;
  export const dossierTombstoneV1Schema: any;
  export const dossierRootReferenceV1Schema: any;
  export const coverageReportV1Schema: any;
  export const selectedEvidenceV1Schema: any;
  export const gateDecisionV1Schema: any;
  export const mainVerificationDecisionV1Schema: any;
  export const certificationHealthDecisionV1Schema: any;
  export const actionAnchorV1Schema: any;
  export const actionDependencyV1Schema: any;
  export const actionTaskV1Schema: any;
  export const certificationActionPackV1Schema: any;
  export const issuerRegistryEntryV1Schema: any;
  export const attestationVerificationV1Schema: any;
  export const signedDecisionV1Schema: any;
  export const signedRootV1Schema: any;
  export const operationAuthorizationV1Schema: any;
  export const nonAuthoritativePreviewV1Schema: any;
  export const artifactReadinessV1Schema: any;
  export const deploymentOperationStateV1Schema: any;
  export const deploymentOperationEventV1Schema: any;
  export const buildReleaseCandidateIdentityV1: any;
  export const buildPolicyBundleIdentityV1: any;
  export const buildEvidenceIdentityV1: any;
  export const buildDossierEventIdentityV1: any;
  export const buildGateDecisionIdentityV1: any;
  export const buildMainVerificationIdentityV1: any;
  export const buildHealthDecisionIdentityV1: any;
  export const buildActionPackIdentityV1: any;
  export const buildDeploymentOperationEventIdentityV1: any;
  export const buildEvidenceIndex: any;
  export const selectRequirementEvidence: any;
  export const EVIDENCE_SELECTION_LIMITS: any;
  export const evaluateCertificationDecision: any;
  export const buildCertificationActionPack: any;
  export const ACTION_PACK_LIMITS: any;
  export const computeDossierEventHash: any;
  export const computeDossierRoot: any;
  export const siteQualityDimensionSchema: any;
  export const certificationGateSchema: any;
  export const requirementClassSchema: any;
  export const remediationClassSchema: any;
  export const driftActionSchema: any;
  export const ownerRoleSchema: any;
  export const producerKindSchema: any;
  export const versionSourceSchema: any;
  export const criticalitySchema: any;
  export const applicabilityRuleV1Schema: any;
  export const freshnessV1Schema: any;
  export const executionV1Schema: any;
  export const remediationV1Schema: any;
  export const reuseV1Schema: any;
  export const certificationRequirementV1Schema: any;
  export const producerDeclarationV1Schema: any;
  export const evaluatorPolicyV1Schema: any;
  export const retentionPolicyV1Schema: any;
  export const certificationProfileV1Schema: any;
  export const profileSourceRefV1Schema: any;
  export const hashCertificationProfileV1: any;
  export const validateCertificationProfileV1: any;
}
